name: Publish Docker image
on:
  push:
    branches:
      - master
  release:
    types:
     - published
jobs:
  push_to_registry:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2

      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push to DockerHub
        uses: docker/build-push-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: ${{ env.GITHUB_REPOSITORY }}
         push: true
         tag_with_ref: true
