name: Publish Docker image
on:
  push:
    branches:
      - master
  release:
    types:
     - published
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2

      -
        name: Prepare
        id: prep
        run: |
          echo ::set-output name=repo-name::$(echo "${GITHUB_REPOSITORY}" | awk -F'/' '{print $2}' | tr '[:upper:]' '[:lower:]')

      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          #tag_with_ref: true
          tags: ahhf/${{ steps.prep.outputs.repo-name }}:latest
